Repository pticostaricags/FairPlaySocial, pull requests merged in 2022-12, with the labels that each got.

#23 Adding UI draft improvements
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/ApplicationUserClientService.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/CustomClaims/CustomAccountClaimsPrincipalFactory.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Pages/Authentication.razor
Labels: enhancement

#34 Fixing issue of modal not showing when clicking on author
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor
Labels: bug

#35 Merge development into main
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor
Labels: bug

#37 Converting to return images as url instead of base64
  src/FairPlaySocialSln/FairPlaySocial.Models/Photo/PhotoModel.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Public/Embedded/Post.razor
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/PostProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFeedController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PublicFeedController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PublicPhotoController.cs
Labels: enhancement

#38 Merge development into main
  src/FairPlaySocialSln/FairPlaySocial.Models/Photo/PhotoModel.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Public/Embedded/Post.razor
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/PostProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFeedController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PublicFeedController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PublicPhotoController.cs
Labels: enhancement

#40 Prohibiting duplicate tags when creating posts
  src/FairPlaySocialSln/FairPlaySocial.CustomValidation/CustomValidationAttributes/ProhibitDuplicateStrings.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/Post/CreatePostModel.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Posts/CreateMyPost.razor
Labels: enhancement

#45 Adding support for Http/3
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MauiProgram.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Program.cs
Labels: enhancement

#57 Enable deleting posts
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyPostClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/Feed.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/Feed.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Posts/Post.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Posts/Post.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyPostController.cs
Labels: enhancement

#58 Create my post client service tests
  src/FairPlaySocialSln/FairPlaySocial.AutomatedTests/ClientServices/ClientServicesTestsBase.cs
  src/FairPlaySocialSln/FairPlaySocial.AutomatedTests/ClientServices/MyPostClientService_Tests.cs
  src/FairPlaySocialSln/FairPlaySocial.AutomatedTests/FairPlaySocial.AutomatedTests.csproj
  src/FairPlaySocialSln/FairPlaySocial.AutomatedTests/Resources/Images/TestImage1.jpg
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyPostController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs
Labels: enhancement

#65 Add localization base
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/CustomLocalization/Api/ApiLocalizer.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/CustomLocalization/Api/ApiLocalizerFactory.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/CustomLocalization/Api/ApiLocalizerOfT.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/FairPlaySocial.ClientServices.csproj
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/LocalizationClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientsConfiguration/ClientsInitialization.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/CustomAttributes/Localization/ResourceKeyAttribute.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Data/FairPlaySocialDatabaseContext.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Culture.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Resource.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/efpt.config.json
  src/FairPlaySocialSln/FairPlaySocial.Database/FairPlaySocial.Database.sqlproj
  src/FairPlaySocialSln/FairPlaySocial.Database/Scripts/PostDeployment/Script.PostDeployment.sql
  src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/Culture.sql
  src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/Resource.sql
  src/FairPlaySocialSln/FairPlaySocial.Models/Localization/CultureModel.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/Localization/ResourceModel.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/FairPlaySocial.SharedUI.csproj
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Index.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/FairPlaySocial.Client.csproj
  src/FairPlaySocialSln/FairPlaySocial/Client/Program.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/LocalizationController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/CustomLocalization/EF/EFStringLocalizerFactory.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/CustomLocalization/EF/EFStringLocalizerOfT.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/CustomLocalization/EF/EfStringLocalizer.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/FairPlaySocial.Server.csproj
  src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs
Labels: enhancement, good first issue

#63 Created PostReach table
  src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/PostReach.sql
Labels: enhancement

#64 Created GroupModerator table
  src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/GroupModerator.sql
Labels: enhancement, good first issue

#67 Integrate azure translator
  src/FairPlaySocialSln/FairPlaySocial.ClientsConfiguration/ClientsInitialization.cs
  src/FairPlaySocialSln/FairPlaySocial.Services/FairPlaySocial.Services.csproj
  src/FairPlaySocialSln/FairPlaySocial.Services/TranslationService.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Extensions/WebAssemblyHostExtensions.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/FairPlaySocial.Client.csproj
  src/FairPlaySocialSln/FairPlaySocial/Client/Program.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Shared/CultureSelector.razor
  src/FairPlaySocialSln/FairPlaySocial/Client/Shared/CultureSelector.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Shared/MainLayout.razor
  src/FairPlaySocialSln/FairPlaySocial/Client/Shared/MainLayout.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/wwwroot/index.html
  src/FairPlaySocialSln/FairPlaySocial/Client/wwwroot/js/blazor-culture.js
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/ResourceProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Translations/BackgroundTranslationService.cs
Labels: enhancement

#70 Adding base for Visitor Tracking and Client Side Error Log
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/ClientSideErrorLogClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/VisitorTrackingClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientsConfiguration/ClientsInitialization.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Extensions/ClaimsExtensions.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Data/FairPlaySocialDatabaseContext.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/ApplicationUser.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/ClientSideErrorLog.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/VisitorTracking.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/efpt.config.json
  src/FairPlaySocialSln/FairPlaySocial.Database/FairPlaySocial.Database.sqlproj
  src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/ClientSideErrorLog.sql
  src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/VisitorTracking.sql
  src/FairPlaySocialSln/FairPlaySocial.Models/ClientSideErrorLog/CreateClientSideErrorLogModel.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/VisitorTracking/VisitorTrackingModel.cs
  src/FairPlaySocialSln/FairPlaySocial.Services/ClientSideErrorLogService.cs
  src/FairPlaySocialSln/FairPlaySocial.Services/FairPlaySocial.Services.csproj
  src/FairPlaySocialSln/FairPlaySocial.Services/VisitorTrackingService.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/App.razor
  src/FairPlaySocialSln/FairPlaySocial/Client/Shared/Error.razor
  src/FairPlaySocialSln/FairPlaySocial/Client/Shared/Error.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Shared/MainLayout.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/VisitorTrackingProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/ClientSideErrorLogController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/VisitorTrackingController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/PlatformServices.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs
Labels: enhancement
