Repository pticostaricags/FairPlaySocial, pull requests merged in 2023-01, with the labels that each got.

#73 Adding localization for menu items
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Index.razor.cs
Labels: enhancement, good first issue

#74 Adding Replies Delete
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Data/FairPlaySocialDatabaseContext.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Post.cs
  src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/Post.sql
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyPostController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PostCommentController.cs
Labels: enhancement

#78 Adding support for passing selected culture to the Azure AD B2C flow
  src/FairPlaySocialSln/FairPlaySocial/Client/Shared/MainLayout.razor.cs
Labels: enhancement

#79 Fixing exception in MAUI app
  src/FairPlaySocialSln/FairPlaySocial.Common/Handlers/LocalizationMessageHandler.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MauiProgram.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Program.cs
Labels: bug

#80 Moving localization to services
  src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/ICultureSelectionService.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MauiProgram.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MultiPlatformServices/MauiCultureSelectionService.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/Shared/MainLayout.razor
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/Shared/MainLayout.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/_Imports.razor
  src/FairPlaySocialSln/FairPlaySocial.MultiplatformComponents/CultureSelector.razor
  src/FairPlaySocialSln/FairPlaySocial.MultiplatformComponents/CultureSelector.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.MultiplatformComponents/FairPlaySocial.MultiplatformComponents.csproj
  src/FairPlaySocialSln/FairPlaySocial/Client/Program.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Services/BlazorCultureSelectionService.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/_Imports.razor
Labels: enhancement

#82 Adding post deployment tests
  .github/workflows/FairPlaySocialDev.yml
  src/FairPlaySocialSln/FairPlaySocial.AutomatedPostDeploymentTests/FairPlaySocial.AutomatedPostDeploymentTests.csproj
  src/FairPlaySocialSln/FairPlaySocial.AutomatedPostDeploymentTests/NavigateToRoot_Tests.cs
  src/FairPlaySocialSln/FairPlaySocial.AutomatedPostDeploymentTests/PostDeploymentTestsBase.cs
  src/FairPlaySocialSln/FairPlaySocial.AutomatedPostDeploymentTests/Usings.cs
  src/FairPlaySocialSln/FairPlaySocialSln.sln
Labels: enhancement

#86 Integrate models localization
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/ApplicationUserClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyFeedClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyFollowClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyLikedPostsClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyPostClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyUserProfileClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/PostCommentClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/PublicFeedClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/PublicUserProfileClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientsConfiguration/ModelsLocalizationSetup.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/FairPlaySocial.Common.csproj
  src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/IGeoLocationService.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/FairPlaySocial.DataAccess.csproj
  src/FairPlaySocialSln/FairPlaySocial.Extensions/FairPlaySocial.Extensions.csproj
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MauiProgram.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MultiPlatformServices/MauiGeoLocationService.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/Extensions/HttpResponseMessageExtensions.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/FairPlaySocial.Models.csproj
  src/FairPlaySocialSln/FairPlaySocial.Models/GeoLocation/GeoCoordinates.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/Post/CreatePostModel.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Program.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Services/BlazorGeoLocationService.cs
  src/FairPlaySocialSln/FairPlaySocialSln.sln
Labels: enhancement

#89 Integrating the base for the DisplayHelper
  src/FairPlaySocialSln/FairPlaySocial.AutomatedTests/ClientServices/ClientServicesTestsBase.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/ClientSideErrorLogClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/VisitorTrackingClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/CustomExceptions/CustomValidationException.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/CustomHelpers/DisplayHelper.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/Extensions/HttpResponseMessageExtensions.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/Post/CreatePostModel.cs
  src/FairPlaySocialSln/FairPlaySocial.Services/ApplicationUserService.cs
  src/FairPlaySocialSln/FairPlaySocial.Services/Utils/ExpressionUtils.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/ImagePicker.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Posts/CreateMyPost.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/_Imports.razor
  src/FairPlaySocialSln/FairPlaySocial/Client/Services/BlazorGeoLocationService.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFeedController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFollowController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyPostController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PostCommentController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PublicFeedController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PublicPhotoController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/ExceptionsHelper.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Program.cs
Labels: enhancement

#90 Integrate app center
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/App.xaml.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/FairPlaySocial.MAUIBlazor.csproj
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/Platforms/Android/MsalActivity.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/appsettings.Development.json
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/appsettings.json
Labels: enhancement

#92 Extend app center usage
  src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/IAnalyticsService.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MauiProgram.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MultiPlatformServices/MauiAnalyticsService.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/Shared/MainLayout.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Index.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Feeds/HomeFeed.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Program.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Services/BlazorAnalyticsService.cs
Labels: enhancement

#93 Creating the GroupService
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Data/FairPlaySocialDatabaseContext.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/ApplicationUser.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Group.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/GroupMember.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/GroupModerator.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Post.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/PostReach.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/efpt.config.json
  src/FairPlaySocialSln/FairPlaySocial.Database/FairPlaySocial.Database.sqlproj
  src/FairPlaySocialSln/FairPlaySocial.Services/GroupService.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/PlatformServices.cs
Labels: enhancement

#94 Creating the MyGroupController
  src/FairPlaySocialSln/FairPlaySocial.Models/Group/CreateGroupModel.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/Group/GroupModel.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/GroupProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyGroupController.cs
Labels: enhancement

#95 Adding MyGroupClientService
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyGroupClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientsConfiguration/ClientsInitialization.cs
Labels: enhancement

#97 Adding the base page for "CreateMyGroup"
  src/FairPlaySocialSln/FairPlaySocial.ClientsConfiguration/ModelsLocalizationSetup.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/INavigationService.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Group.partial.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/Group/CreateGroupModel.cs
  src/FairPlaySocialSln/FairPlaySocial.MultiplatformServices/NavigationService.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Index.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Groups/CreateMyGroup.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Groups/CreateMyGroup.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyGroupController.cs
Labels: enhancement

#99 Adding the basic SearchService
  src/FairPlaySocialSln/FairPlaySocial.Services/SearchService.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/PlatformServices.cs
Labels: enhancement

#101 Adding base for the SearchController
  src/FairPlaySocialSln/FairPlaySocial.Models/UserProfile/UserProfileModel.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/UserProfileProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/SearchController.cs
Labels: enhancement

#103 Adding the SearchClientService
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/SearchClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.ClientsConfiguration/ClientsInitialization.cs
Labels: enhancement

#105 Implementing the basic Search from the UI
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/SearchClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/INavigationService.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/Search/SearchModel.cs
  src/FairPlaySocialSln/FairPlaySocial.MultiplatformComponents/Bootstrap/Card.razor
  src/FairPlaySocialSln/FairPlaySocial.MultiplatformComponents/Bootstrap/Card.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.MultiplatformServices/NavigationService.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/SearchModal.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/SearchModal.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchUserProfiles.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchUserProfiles.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/Shared/MainLayout.razor
Labels: enhancement

#107 Adding the search component to the maui app
  .github/workflows/Dev_Branch_Build.yml
  .github/workflows/FairPlaySocialDev.yml
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/Shared/MainLayout.razor
Labels: enhancement

#109 Updating the BlazoredToast Library
  src/FairPlaySocialSln/FairPlaySocial/Client/FairPlaySocial.Client.csproj
Labels: enhancement

#111 Creating the SearchGroups page
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/SearchModal.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor.cs
Labels: enhancement

#113 Enabling the ability to join groups
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyGroupClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Data/FairPlaySocialDatabaseContext.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Group.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/GroupMember.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/GroupMember.partial.cs
  src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/GroupMember.sql
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/wwwroot/index.html
  src/FairPlaySocialSln/FairPlaySocial.Services/GroupMemberService.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Client/wwwroot/index.html
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyGroupController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/PlatformServices.cs
Labels: enhancement

#115 Adding group feed
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/MyFeedClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/IAnalyticsService.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/INavigationService.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Data/FairPlaySocialDatabaseContext.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Group.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Post.cs
  src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/Post.sql
  src/FairPlaySocialSln/FairPlaySocial.Models/Post/CreatePostModel.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/Post/CreateSharedPostModel.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/Post/PostModel.cs
  src/FairPlaySocialSln/FairPlaySocial.MultiplatformServices/NavigationService.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/PostComponent.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Feeds/GroupFeed.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Feeds/GroupFeed.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Posts/CreateMyPost.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/Search/SearchGroups.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFeedController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyPostController.cs
Labels: enhancement

#117 Adding Server Rate Limit
  src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFeedController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs
Labels: enhancement

#119 Introducing Output Caching for Localization Endpoints
  src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/LocalizationController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/OutputCacheExtensions.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/RateLimiterExtensions.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs
Labels: enhancement

#120 Update packages
  src/FairPlaySocialSln/FairPlaySocial.AutomatedPostDeploymentTests/FairPlaySocial.AutomatedPostDeploymentTests.csproj
  src/FairPlaySocialSln/FairPlaySocial.ClientServices.Generators/FairPlaySocial.ClientServices.Generators.csproj
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/FairPlaySocial.ClientServices.csproj
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/FairPlaySocial.DataAccess.csproj
  src/FairPlaySocialSln/FairPlaySocial.Server.Generators/FairPlaySocial.Server.Generators.csproj
  src/FairPlaySocialSln/FairPlaySocial.Services.Generators/FairPlaySocial.Services.Generators.csproj
  src/FairPlaySocialSln/FairPlaySocial.Services/FairPlaySocial.Services.csproj
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/FairPlaySocial.SharedUI.csproj
  src/FairPlaySocialSln/FairPlaySocial/Server/FairPlaySocial.Server.csproj
Labels: enhancement

#127 Integrating with Azure Text Analytics
  src/FairPlaySocialSln/FairPlaySocial.AutomatedTests/ClientServices/MyPostClientService_Tests.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Data/FairPlaySocialDatabaseContext.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/Post.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/PostKeyPhrase.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/efpt.config.json
  src/FairPlaySocialSln/FairPlaySocial.Database/FairPlaySocial.Database.refactorlog
  src/FairPlaySocialSln/FairPlaySocial.Database/FairPlaySocial.Database.sqlproj
  src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/PostKeyPhrase.sql
  src/FairPlaySocialSln/FairPlaySocial.Services/ErrorLogService.cs
  src/FairPlaySocialSln/FairPlaySocial.Services/FairPlaySocial.Services.csproj
  src/FairPlaySocialSln/FairPlaySocial.Services/PostKeyPhraseService.cs
  src/FairPlaySocialSln/FairPlaySocial.Services/TextAnalyticsService.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyPostController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/PlatformServices.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs
Labels: enhancement

#130 Add xml comments to the Server project
  src/FairPlaySocialSln/FairPlaySocial.Server.Generators/ControllersIncrementalGenerator.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/ApplicationUserFollowProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/ApplicationUserProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/DislikedPostProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/GroupProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/LikedPostProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/PhotoProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/PostProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/PostTagProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/ResourceProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/UserPreferenceProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/UserProfileProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/VisitorTrackingProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/ApplicationUserController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/AuthController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/LocalizationController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFeedController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyFollowController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyGroupController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyLikedPostsController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyPostController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyUserPreferenceController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/MyUserProfileController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PhotoController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PostCommentController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PublicFeedController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PublicPhotoController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/PublicUserProfileController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/SearchController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/VisitorTrackingController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/ExceptionsHelper.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/FairPlaySocial.Server.csproj
  src/FairPlaySocialSln/FairPlaySocial/Server/OutputCacheExtensions.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Pages/Error.cshtml.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/PlatformServices.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/RateLimiterExtensions.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Startup.cs
Labels: enhancement, good first issue

#134 Adding the base classes for supporting User Messages
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Data/FairPlaySocialDatabaseContext.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/ApplicationUser.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/Models/UserMessage.cs
  src/FairPlaySocialSln/FairPlaySocial.DataAccess/efpt.config.json
  src/FairPlaySocialSln/FairPlaySocial.Database/FairPlaySocial.Database.sqlproj
  src/FairPlaySocialSln/FairPlaySocial.Database/dbo/Tables/UserMessage.sql
  src/FairPlaySocialSln/FairPlaySocial.Models/UserMessage/CreateUserMessageModel.cs
  src/FairPlaySocialSln/FairPlaySocial.Models/UserMessage/UserMessageModel.cs
  src/FairPlaySocialSln/FairPlaySocial.Services/UserMessageService.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/UserMessageController.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/PlatformServices.cs
Labels: enhancement

#142 Add messages list
  src/FairPlaySocialSln/FairPlaySocial.ClientServices/UserMessageClientService.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Global/Constants.cs
  src/FairPlaySocialSln/FairPlaySocial.Common/Interfaces/Services/INavigationService.cs
  src/FairPlaySocialSln/FairPlaySocial.CustomValidation/CustomValidationAttributes/ProhibitHashTagsAttribute.cs
  src/FairPlaySocialSln/FairPlaySocial.CustomValidation/CustomValidationAttributes/ProhibitUrlsAttribute.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/App.xaml.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/FairPlaySocial.MAUIBlazor.csproj
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/Resources/Images/dotnet_bot.svg
  src/FairPlaySocialSln/FairPlaySocial.MultiplatformComponents/AudibleLabel.razor
  src/FairPlaySocialSln/FairPlaySocial.MultiplatformComponents/AudibleLabel.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.MultiplatformServices/NavigationService.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Components/MessageComposer.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/Index.razor.cs
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/UserMessages/UserMessages.razor
  src/FairPlaySocialSln/FairPlaySocial.SharedUI/Pages/User/UserMessages/UserMessages.razor.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/AutoMapperProfiles/UserMessageProfile.cs
  src/FairPlaySocialSln/FairPlaySocial/Server/Controllers/UserMessageController.cs
  src/FairPlaySocialSln/FairPlaySocialSln.sln
Labels: enhancement

#146 Making MAUI use Blazored Toast
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/App.xaml.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/FairPlaySocial.MAUIBlazor.csproj
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MauiProgram.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MultiPlatformServices/BlazorToastService.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/MultiPlatformServices/MauiToastService.cs
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/Shared/MainLayout.razor
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/_Imports.razor
  src/FairPlaySocialSln/FairPlaySocial.MAUIBlazor/wwwroot/index.html
Labels: bug
